In [82]:
# Math 364-Spring 2020, Instructor: Mostafa Rezapour
# Python Tutorial 1

#Lists: A list can contain elements of different types. In Python a list is different from a vector.

x=[1,2,3]
print('x=',x) 
y=[4,5,6]
print('y=',y)
x.append(6)
print('new x=',x)

x= [1, 2, 3]
y= [4, 5, 6]
new x= [1, 2, 3, 6]


In [83]:
# In Python the first index is zero.
print('The first element in the list is equal to', x[0])

The first element in the list is equal to 1


In [84]:
print(x[1],x[2],x[3],x[-1])

2 3 6 6


In [85]:
#Python provides concise syntax to access sublists
y=list(range(7))
print('y=',y)

y= [0, 1, 2, 3, 4, 5, 6]


In [86]:
print(y[0:2])

[0, 1]


In [87]:
print(y[2:5])

[2, 3, 4]


In [88]:
#Loops. You can loop over the elements:
z=list(range(4))
for i in z:
    print(z[i])


0
1
2
3


In [89]:
Mostafa_interests=['Optimization', 'Machine-Learning', 'Deep-Learning', 'Data-Analysis']
for i in Mostafa_interests:
    print(i)


Optimization
Machine-Learning
Deep-Learning
Data-Analysis


In [90]:
Mostafa_interests=['Optimization', 'Machine-Learning', 'Deep-Learning', 'Data-Analysis']
index=1
for i in Mostafa_interests:
    print(index,'=',i)


1 = Optimization
1 = Machine-Learning
1 = Deep-Learning
1 = Data-Analysis


In [91]:
def abs(x):
    if x>=0:
        return x
    else: 
        return -x

#example
a1=abs(2)
a2=abs(-6)
[a1,a2], # a list 


([2, 6],)

In [92]:
def my_function(x,y,z):
    return (x*y)**2+z
#example 
my_function(2,3,4)

    

40

In [93]:
def your_function(x,y,z):
    a=x+y
    b=x*y
    c=x+y+z
    return [a,b,c]

#example
your_function(1,2,3)
    

[3, 2, 6]

In [94]:
# How can we store an array in Python? Using Numpy library
import numpy as np
ar1=np.array([1,2,3])
print('array1=',ar1, 'and its type is', type(ar1))
li1=[1,2,3]
print('list1=',li1, 'and its type is', type(li1))



array1= [1 2 3] and its type is <class 'numpy.ndarray'>
list1= [1, 2, 3] and its type is <class 'list'>


In [95]:
ar1[0]

1

In [96]:
li1[0]

1

In [97]:
ar2=np.array([4,5,6])
li2=[4,5,6]
print(np.shape(ar2))
print(np.shape(li2))



(3,)
(3,)


In [98]:
A=[[1,2,3],[4,5,6]]
A
print(np.shape(A))
print(type(A))

(2, 3)
<class 'list'>


In [99]:
B=np.transpose(A)
B
print(np.shape(B))
print(type(B))

(3, 2)
<class 'numpy.ndarray'>


In [100]:
A[0]

[1, 2, 3]

In [101]:
A[1]

[4, 5, 6]

In [102]:
A[0][0]

1

In [103]:
A[1][0]

4

In [104]:
AA=np.array([[1,2,3],[4,5,6]])
AA
print(np.shape(AA))
print(type(AA))

(2, 3)
<class 'numpy.ndarray'>


In [105]:
BB=np.array([[11,21,31],[41,51,61]])
BB
print(np.shape(BB))
print(type(BB))

(2, 3)
<class 'numpy.ndarray'>


In [106]:
AA+BB

array([[12, 23, 34],
       [45, 56, 67]])

In [107]:
print(AA.transpose())

[[1 4]
 [2 5]
 [3 6]]


In [108]:
AAt=np.transpose(AA)
AAt
print(np.shape(AAt))

(3, 2)


In [109]:
# Matrix Multiplication
CC=np.matmul(AAt,BB)
print(CC,'\n and its dimension is', np.shape(CC))

[[175 225 275]
 [227 297 367]
 [279 369 459]] 
 and its dimension is (3, 3)
